### PR TITLE
support django 1.11

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@orf I've cleaned up your PR and restored the current approach with CI on Travis.

**Comment by orf** [comment]
Ok, thanks @graingert, it looks good.

Why did you revert the CI approach? tox-travis looks like a great idea?

**Comment by graingert** [comment]
I just want to make the minimum changes possible to support django1.11

**Comment by orf** [comment]
Fair enough, that makes sense. These changes look good and we've deployed them with our application, and the library works as expected.

Can this be pushed to a new release?

**Pull request merged**
