### PR TITLE
Added a failing test for issue #27

### PR DESCRIPTION
**Pull request by benwad**

### CODE REVIEW

**Comment by graingert** [comment]
@benwad won't this need to have Babel installed to work?

**Comment by graingert** [comment]
@sils1297 any idea why this PR isn't building on Travis?

**Comment by sils1297** [comment]
@graingert maybe the hook got lost due to a downtime on travis side? There was a github outage on 8th but this shouldn't be affected. @benwad you can `git commit --amend`, save and `git push --force` to resync your branch which will push a new commit with the same contents to github and retrigger CI.

Alternatively you can push an empty commit on top if your policy is against force pushes: `git commit --allow-empty`.

**Comment by graingert** [comment]
@sils1297 I :heart: force pushes

**Comment by sils1297** [comment]
@graingert me too :) Though it's hard to get people to write proper commits using that if they never used git before and a word of caution is in order especially since some of those people even use master for development...

**Comment by graingert** [comment]
@benwad won't this need to have Jinja2 installed to work?

**Comment by graingert** [comment]
issue #27

**Comment by benwad** [comment]
@graingert sorry for the delay, yes this will need Jinja2. Where do I need to add that requirement for the test?

**Comment by graingert** [comment]
@benwad https://github.com/python-babel/django-babel/blob/master/tox.ini#L5

**Comment by benwad** [comment]
@graingert thanks, I've pushed the change.

**Comment by graingert** [comment]
@benwad you also need to rebase this PR

**Comment by graingert** [comment]
@benwad I'm also pretty sure you need to configure django to enable Jinja2, and configure your Jinja2 environment, and disable the tests on Django versions without pluggable template engines.

**Comment by graingert** [comment]
As discussed in the issue, you should use the babel Jinja2 library to get this to work.

**Pull request closed without merging**
