### PR TITLE
Add support for "trimmed" blocktrans content

### PR DESCRIPTION
**Pull request by robhudson**

### CODE REVIEW

**Comment by robhudson** [comment]
This fixes #20

**Comment by willkg** [comment]
@graingert How does this look? Do you need us to do anything?

**Comment by willkg** [comment]
Friendly ping. How does this look? Do you need us to do anything?

**Comment by graingert** [comment]
@willkg I'm really sorry, I've only just got the emails from this thread. I'll have a look after the weekend

**Comment by graingert** [comment]
I'm going to remove support for all out of support Django and python versions. So that should simplify your PR

**Comment by amotoki** [comment]
@graingert Is there any progress on review of this PR? I am really waiting for a new release with this PR.

**Comment by graingert** [comment]
@amotoki try pinging @mrunge

**Comment by mrunge** [comment]
Will look at that asap. Unfortunately, I'm deeply buried in some mud hole currently.

**Comment by mrunge** [comment]
Thank you for your contribution!

**Comment by graingert** [comment]
@mrunge did you mean to close this?

**Comment by mrunge** [comment]
@graingert Uhm, I thought I pushed "merge" before, the commit looks sane to me.

**Comment by graingert** [comment]
@mrunge :p oops

**Comment by mrunge** [comment]
Now finally: @robhudson thank you for your contribution, I'll tag it into release asap.

**Pull request merged**
