### PR TITLE
Various fixes, sync of our repos.

### PR DESCRIPTION
**Pull request by EnTeQuAk**

### CODE REVIEW

**Comment by graingert** [comment]
Cool looks good to me.

**Comment by graingert** [comment]
@EnTeQuAk can you rebase this change and cleanup the commits?

**Comment by EnTeQuAk** [comment]
@graingert what do you mean by "cleanup the commits"? I would not want to squash them since they all make sense on their own I think.

Regarding the rebase, sure, I can do this some time today.

**Comment by graingert** [comment]
probably best to do a merge rather than a rebase in this case, because these commits are published on PyPI with tags etc.

**Comment by EnTeQuAk** [comment]
Right, that's what I wanted to ask.


On Mon, Sep 21, 2015, at 06:44 PM, Thomas Grainger wrote:
> probably best to do a merge rather than a rebase in this case, because
> these commits are published on PyPI with tags etc.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/python-babel/django-babel/pull/7#issuecomment-142038719

**Pull request merged**
